#!/bin/bash

export BB_PATH=`dirname ${BASH_SOURCE[0]}`
export PATH="$BB_PATH/bin:$PATH"

# add BB_INSTALL to .bashrc to 
# define where bio.brew will install
# tools
if [ -z "$BB_INSTALL" ]
then
  export BB_INSTALL=$BB_PATH/local
fi

export PATH="$BB_INSTALL/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$BB_INSTALL/lib"

BB_LOGS_DIR="$BB_PATH/logs"

if [ `ls $BB_LOGS_DIR/**/*.sh 2>/dev/null | wc -l` != "0" ]
then
  for s in $BB_LOGS_DIR/**/*.sh
  do
    source $s
  done
fi

